In [2]:
import torch

In [3]:
# kuch nai hai bhai sab same numpy type hi hai shape size dtpye etc  

In [ ]:
x = torch.randn((3,4))

print(x)


tensor([[-0.5567, -1.1423, -0.0158,  0.2982],
        [ 2.2269,  1.4839, -0.4477, -0.0749],
        [-2.2221, -0.8496,  1.2997,  0.2621]])


In [16]:
img = torch.randn(3,224,224)
img.dtype

torch.float32

In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a+b)
print(a-b)
print(a*b)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])


In [26]:
# torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

x = torch.randn(1000,1000).to(device)

print(x.device)

cuda:0


In [30]:
x = torch.tensor(
    3.0,
    requires_grad=True
)
# require grad monitor karta hai regularly for any change in x for y like 
# if y changes tehn it will knwow here to find x ig
y = x**2 + 2*x

y.backward()

print(x.grad)

tensor(8.)


In [35]:
torch.Size(torch.arange(12))
torch.arange(12).reshape(3,4).T


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])